
const http = require('http');
  
  const server = http.createServer((req, res) => {
    
    if (req.url === '/') {
      res.writeHead(200, { 'Content-Type': 'text/html' });
      res.end( `
        <div style="text-align: center;">
          <h2>Hello!
          <br>
          This page is generated by a Node Server in the Browser!
          </h2>
        </div>
        ` );

    } else if( req.url === '/request/time' ) { 
      res.writeHead(200, { 'Content-Type': 'text/html' });
      res.end( `
        <div style="text-align: center;">
          <h2>Timestamp: ${ new Date().toISOString() }</h2> <!-- senza ; -->
        </div>
        ` );

    } else if( req.url === '/request/day' ) {
      var dayNumb = new Date().getDay(); 
      const daysOfWeek = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
      res.writeHead(200, { 'Content-Type': 'text/html' });
      res.end( `
        <div style="text-align: center;">
          <h2>Day of the week: ${ "" + daysOfWeek[ dayNumb ] + " (" + dayNumb + ")" }</h2> <!-- senza ; -->
        </div>
        ` );

    } else if( req.url.includes( '/request/sum' ) ) {
      //console.log( req.url )
      const urlParams = new URLSearchParams( ("" + req.url ).split('?')[1]); 
      var value01 = urlParams.get('value01'); 
      var value02 = urlParams.get('value02');
      res.writeHead(200, { 'Content-Type': 'text/html' });
      res.end( `
        <div style="text-align: center;">
          <h2>Sum of ${value01}, ${value02}: ${ ( parseInt(value01, 10) + parseInt(value02, 10) ) }</h2> <!-- senza ; -->
        </div>
        ` );

    }
  });
  
  server.listen(3000, () => {
    console.log('Server virtuale in ascolto sulla porta 3000');
  });
  